config/routes.rb
TransResourceFinder::Application.routes.draw do

	root :to => "resources#index"
  namespace :api, :defaults => {:format => 'json'} do
    namespace :v1, :constraints => ApiConstraints.new(:version => 1) do
      resources :resources, :only => [:show, :index]
      resources :categories, :only => [:index]
    end
  end

  resources :resources, :only => [:create, :new, :index, :edit, :update]
end

app/views/resources/_form.html.erb
<%= form_for @resource do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :category %>:
  <%= f.collection_select( :category_id, Category.all, :id, :name) %><br />

  <%= f.label :accessibility_rating %>:
  <%= f.number_field :accessibility_rating, :min => "1", :max => "5" %><br />

  <%= f.label :trans_friendliness_rating %>:
  <%= f.number_field :trans_friendliness_rating, :min => "1", :max => "5" %><br />

  <%= f.label :service_quality_rating %>:
  <%= f.number_field :service_quality_rating, :min => "1", :max => "5" %><br />

  <%= f.label :street_address_1%>:
  <%= f.text_field :street_address_1 %><br />

  <%= f.label :street_address_2%>:
  <%= f.text_field :street_address_2 %><br />

  <%= f.label :city%>:
  <%= f.text_field :city %><br />

  <%= f.label :state%>:
  <%= f.text_field :state %><br />

  <%= f.label :zip%>:
  <%= f.text_field :zip %><br />

  <%= f.label :phone%>:
  <%= f.telephone_field :phone %><br />

  <%= f.label :website%>:
  <%= f.text_field :website %><br />

  <%= f.label :email%>:
  <%= f.email_field :email %><br />

  <%= f.label :contact_name%>:
  <%= f.text_field :contact_name %><br />

  <%= f.label :services_offered %>:
  <%= f.text_area :services_offered %><br />

  <%= f.label :people_served%>:
  <%= f.text_area :people_served%><br />

  <%= f.label :accessibility%>:
  <%= f.text_area :accessibility %><br />

  <%= f.label :notes%>:
  <%= f.text_area :notes %><br />

  <%= f.submit %>
<% end %>

app/views/resources/_map.html.erb
<section id="map-section">
  <header class="clearfix">

    <form id="locate" action="/" class="width">
      <h3>Find trans-friendly services:</h3>
      <div class="form-responsive">
        <div class="styled-select">
          <%= select_tag 'category', options_from_collection_for_select(@categories, :name, :name), :prompt => "Category" %>
        </div>
        <div class="form-responsive-2">
          <%= text_field_tag :zip, nil, :maxlength => 5, :placeholder => "Zip Code", :pattern => "\\d*" %>
          <%= submit_tag "Go!" %>
        </div><!-- /form-responsive-2 -->
      </div><!-- /form-responsive -->
    </form>
  </header>
  <div id="map-container">
    <div id="map">
    </div>
    <div class="modal"><!-- Place at bottom of page --></div>
  </div>
</section><!-- /map -->

<%= render :partial => 'results' %>

app/views/resources/_resource.html.erb
<li>
  <%= resource.name %>
</li>

app/views/resources/_results.html.erb
<section id="results" class="clearfix">
  <div class="width">
    <%= link_to "Add a resource +", new_resource_path, :class => 'add-resource' %>
    <div id="locations"></div>
    <div id="pager"></div>


  </div>

</section><!-- /results -->

app/views/resources/edit.html.erb
<div class="width clearfix" id="main-section">
  <h3>Edit Resource: <%= @resource.name %></h3>

<%= render :partial => 'form' %>

</div>

app/views/resources/index.html.erb
<section id="about">
  <div class="width">
    <div class="textfill">Trans*ResourceUS's mission is to provide a comprehensive web and mobile application that empowers, stabilizes, uplifts and creates community solidarity by providing a search engine for employment, housing and health information.</div>
  </div>
</section><!-- /about -->

<%= render :partial => 'map' %>

app/views/resources/new.html.erb
<div class="width clearfix" id="main-section">
  <h3>Add New Resource</h3>

<%= form_for @resource do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :category %>:
  <%= f.collection_select( :category_id, Category.all, :id, :name) %><br />

  <%= f.label :accessibility_rating %>:
  <%= f.number_field :accessibility_rating, :min => "1", :max => "5" %><br />

  <%= f.label :trans_friendliness_rating %>:
  <%= f.number_field :trans_friendliness_rating, :min => "1", :max => "5" %><br />

  <%= f.label :service_quality_rating %>:
  <%= f.number_field :service_quality_rating, :min => "1", :max => "5" %><br />

  <%= f.label :street_address_1%>:
  <%= f.text_field :street_address_1 %><br />

  <%= f.label :street_address_2%>:
  <%= f.text_field :street_address_2 %><br />

  <%= f.label :city%>:
  <%= f.text_field :city %><br />

  <%= f.label :state%>:
  <%= f.text_field :state %><br />

  <%= f.label :zip%>:
  <%= f.text_field :zip %><br />

  <%= f.label :phone%>:
  <%= f.telephone_field :phone %><br />

  <%= f.label :website%>:
  <%= f.text_field :website %><br />

  <%= f.label :email%>:
  <%= f.email_field :email %><br />

  <%= f.label :contact_name%>:
  <%= f.text_field :contact_name %><br />

  <%= f.label :services_offered %>:
  <%= f.text_area :services_offered %><br />

  <%= f.label :people_served%>:
  <%= f.text_area :people_served%><br />

  <%= f.label :accessibility%>:
  <%= f.text_area :accessibility %><br />

	<%= f.label :notes%>:
  <%= f.text_area :notes %><br />

  <%= f.submit %>
<% end %>

</div>